# Generated by Django 2.1.2 on 2018-11-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='ceto', max_length=100),
            preserve_default=False,
        ),
    ]
