# Generated by Django 2.1.2 on 2018-11-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_servicios_turistico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turistico',
            name='foto',
            field=models.ImageField(upload_to='fotos/'),
        ),
    ]
