# Generated by Django 2.1.2 on 2018-11-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_turistico_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turistico',
            name='descripcion',
            field=models.CharField(max_length=1500),
        ),
    ]
