# Generated by Django 2.1.2 on 2018-11-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20181113_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='link',
        ),
        migrations.AddField(
            model_name='servicios',
            name='archivo',
            field=models.FileField(default='nada', upload_to='archivos/'),
            preserve_default=False,
        ),
    ]
