# Generated by Django 2.1.2 on 2018-11-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20181113_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='orga',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rut',
        ),
    ]
